### ISSUE TITLE
AttributeError: can't set attribute 'headless'

### ISSUE THREAD

**Issue by Whitewolf342** [9P9/Discord-QR-Token-Logger#30]
![image](https://user-images.githubusercontent.com/74878033/189725599-283818cc-d262-420c-a7fd-55508e02681e.png)

Getting This Issue, Any Solution?

**Comment by mouadessalim** [comment]
Hey @Whitewolf342, actually you're error may occur because of your chrome version. We need to have your chrome version and python version.

**However please consider :** 

This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md). Thank you for updating the issue or closing it. In case of no change, the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The issue doesn't respect these instructions:**

https://github.com/9P9/Discord-QR-Token-Logger/blob/19251c32fa13e91f315c9a3e095e87952167eed5/CONTRIBUTING.md?plain=1#L37

https://github.com/9P9/Discord-QR-Token-Logger/blob/19251c32fa13e91f315c9a3e095e87952167eed5/CONTRIBUTING.md?plain=1#L58

https://github.com/9P9/Discord-QR-Token-Logger/blob/19251c32fa13e91f315c9a3e095e87952167eed5/CONTRIBUTING.md?plain=1#L59

**Comment by Whitewolf342** [comment]
My Chrome Version is : Version 105.0.5195.127 (Official Build) (64-bit)
My Python Version is : Python 3.10.7 ( The Latest one )

OS : Windows 10
System Type : 64-bit operating system, x64-based processor

**Comment by mouadessalim** [comment]
Hey @Whitewolf342 thanks for responding, actually you're error is kinda weird because you have one of the lastest chrome version so i don't know why you error occur. For now i am not able to work alone on the bug i may need you're help because i don't have you error when using the script. This mean that it occur with a specific environnement. Can you please use this version and send me back if it's good. If not please send me the error.

https://github.com/9P9/Discord-QR-Token-Logger/blob/30-attributeerror-cant-set-attribute-headless/Discord-QR-Token-Logger.py

**Comment by Whitewolf342** [comment]
[!] Generating Qr-Code...Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USER\Desktop\test\Discord-QR-Token-Logger-30-attributeerror-cant-set-attribute-headless\Discord-QR-Token-Logger.py", line 54, in main
    main.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=opts)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

**Comment by mouadessalim** [comment]
> ```
> Traceback (most recent call last):
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\USER\Desktop\test\Discord-QR-Token-Logger-30-attributeerror-cant-set-attribute-headless\Discord-QR-Token-Logger.py", line 54, in main
>     main.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=opts)
> TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'```
> ```

okay @Whitewolf342 please try in the command line : `pip install selenium --upgrade`

**Comment by Whitewolf342** [comment]
Okay its working but where do i get the QR code to send to target?

![image](https://user-images.githubusercontent.com/74878033/190255346-1809f667-d306-46ab-837f-ac56f5b8086a.png)

**Comment by mouadessalim** [comment]
finally it's working 🥳 yes when showing this the discord_gift img while appair in the same folder than script.

**Comment by Whitewolf342** [comment]
Oh okay i got it now thanks
