### ISSUE TITLE
Erreur avec chrome drive

### ISSUE THREAD

**Issue by Cleboost** [9P9/Discord-QR-Token-Logger#4]
![image](https://user-images.githubusercontent.com/61158869/142450824-50034cb3-a692-47f9-9b7e-c3621149200b.png)

**Comment by rockpapersissors** [comment]
Tu sais pas lire ou quoi? This version of chromeDriver only supports version 89
Current browser version is 96 , incompatible facile a comprendre pourtant..

**Comment by ChristianPenev** [comment]
Hi @Cleboost, sorry for the late answer but I just saw your question. You are getting this error because you are using a wrong chromedriver version. It should be the same as the version of your browser. The most common version right now is 96 but your can be different. What you have to do is to download  the right chromedriver and delete the older one. If you have any additional questions add me on Discord (ChristianPenev#1315)

**Comment by Cleboost** [comment]
Oh yes, you are right. 
Thank your for your help. 
Kind regards

**Comment by WakeysCode** [comment]
> Hi @Cleboost, sorry for the late answer but I just saw your question. You are getting this error because you are using a wrong chromedriver version. It should be the same as the version of your browser. The most common version right now is 96 but your can be different. What you have to do is to download the right chromedriver and delete the older one. If you have any additional questions add me on Discord (ChristianPenev#1315)

Hello, there isn't an available chrome driver version for the latest chrome 97.0.4692.99. And i don't know how to downgrade Chrome, i found Slimjet but there wasn't a single chrome driver version for the version listed there either. I have no idea how to proceed
