### ISSUE TITLE
pywin32

### ISSUE THREAD

**Issue by PepsiNitro** [9P9/Discord-QR-Token-Logger#54]
ERROR: Could not find a version that satisfies the requirement pywin32==305 (from versions: none)
ERROR: No matching distribution found for pywin32==305

Got this message after running pip install -r requirements.txt, some stuff started downloading then it stopped with this error message
(Also I'm using Gitpod to run this)
How do I fix this?

**Comment by mouadessalim** [comment]
Gitpod may be the problem, try to install the module outside of the Gitpod env because the module exist you can check it here: https://github.com/mhammond/pywin32/releases/tag/b305 or here https://pypi.org/project/pywin32/305/

**Comment by mouadessalim** [comment]
on windows 10, you can use python venv if you want

**Comment by mouadessalim** [comment]
After some research Gitpod env are working with Ubuntu servers which is not supported by the project, you need to have a windows machine to use it.

 This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md). Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The issue doesn't respect this instruction:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/17b30be127aef9ad81a0ab1d93718f275795aab5/CONTRIBUTING.md?plain=1#L29

https://github.com/9P9/Discord-QR-Token-Logger/blob/0caeb6882f1c07b747319deb6f23a91dfe807c12/README.md?plain=1#L100-L104

`pywin32` module is a windows module since it's working with windows API. This is why the env is not capable of finding it.

@PepsiNitro
