### ISSUE TITLE
what is proxy?

### ISSUE THREAD

**Issue by l3qso** [9P9/Discord-QR-Token-Logger#79]
what do i do here?

![image](https://github.com/9P9/Discord-QR-Token-Logger/assets/129872317/584e489c-d10f-4b38-abc3-4ef817ef1898)

**Comment by the-cult-of-integral** [comment]
A proxy is like an extra layer of privacy. When make a network request, the first thing they'll see as the request IP is the proxy IP rather than your real IP. You can chain proxies together in what is known as a proxy chain.

I highly doubt you're going to have the FBI knocking on your door just because you stole someone's discord token though, but the option is there if you want that extra precaution.

**Comment by l3qso** [comment]
Where do i find it to enter it there

**Comment by l3qso** [comment]
Or skip it?

**Comment by Bang-Bang-Ban** [comment]
> A proxy is like an extra layer of privacy. When make a network request, the first thing they'll see as the request IP is the proxy IP rather than your real IP. You can chain proxies together in what is known as a proxy chain.
> 
> I highly doubt you're going to have the FBI knocking on your door just because you stole someone's discord token though, but the option is there if you want that extra precaution.

no you fucking dumbass its so you use the same authserver lmfao

**Comment by Bang-Bang-Ban** [comment]
how to have contributor role when you're fucking stuupid

**Comment by l3qso** [comment]
> how to have contributor role when you're fucking stuupid

Shush lil nigga and spread those legs

**Comment by Bang-Bang-Ban** [comment]
say less 😩

**Comment by mouadessalim** [comment]
> how to have contributor role when you're fucking stuupid

In reality you are right, the proxy is to use the same auth server as discord to bypass discord firewalls. Not to be found by the FBI. And secondly it's for educational purpose.

**Comment by mouadessalim** [comment]
> A proxy is like an extra layer of privacy. When make a network request, the first thing they'll see as the request IP is the proxy IP rather than your real IP. You can chain proxies together in what is known as a proxy chain.
> 
> I highly doubt you're going to have the FBI knocking on your door just because you stole someone's discord token though, but the option is there if you want that extra precaution.

No, I've added a proxy feature to bypass Discord firewalls. If you try it with yourself, it will work because you're using IP addresses from the same country. However, if you use it with someone outside your country, it won't work. This is because Discord's server detects a mismatch between a person connecting with their phone in one country (Country A) and being connected on a PC in another country (Country B). Therefore, this results in an unauthorized request and authentication failure.

**Comment by Bang-Bang-Ban** [comment]
> No, I've added a proxy feature to bypass Discord firewalls. If you try it with yourself, it will work because you're using IP addresses from the same country. However, if you use it with someone outside your country, it won't work. This is because Discord's server detects a mismatch between a person connecting with their phone in one country (Country A) and being connected on a PC in another country (Country B). Therefore, this results in an unauthorized request and authentication failure.
T
o add on the main way it does this is by using the authserver associated with your region, if they  mismatch then youre in different regions (example wss://gateway-us-east1-c.discord.gg/)
