### ISSUE TITLE
Help :p

### ISSUE THREAD

**Issue by Sneekydeer45** [9P9/Discord-QR-Token-Logger#9]
![help](https://user-images.githubusercontent.com/91907771/167018813-79bee850-7119-4f0a-b236-e3e91fd20964.png)
idk

**Comment by ThatTSGuy** [comment]
This is the working one: https://github.com/ThatTSGuy/discord-qr-token-grabber

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue will be closed in _**48 hours**_. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The issue doesn't respect these instructions:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md?plain=1#L36-L37

https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md?plain=1#L52

@Sneekydeer45  @9P9

**Comment by mouadessalim** [comment]
Thank you @ThatTSGuy for deleting this [comment](https://github.com/9P9/Discord-QR-Token-Logger/issues/9#issuecomment-1186523757) because it doens't respect [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md). Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The  [comment](https://github.com/9P9/Discord-QR-Token-Logger/issues/9#issuecomment-1186523757) doesn't respect this instruction:**

https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md?plain=1#L22-L23
